hot = ["It's as hot as a freashly baked pie!", 
       "It's about as hot as the sun!", 
       "When you complain about the cold, remember days like this!",
       "It's so hot, even the cactuses are sweating!",
       "They say a desert is hot, but you could cook dessert on this pavement!",
       "It is so hot i think eating a chili pepper would be cooler!,"
       "If it gets any hotter, I'll have to take off stuff I really ought to keep on!",
       "I'm just roasting!",
       "It's like walking through soup out here.",
       "It's so hot the ice-cream truck melted.",
       "Hotter than the devil’s armpit",
       "Hotter than hell’s pepper patch",
       "It’s so hot my dream house in any house in Alaska.",
       "It’s so hot, when the temperature drops below 95 I start to feel chilly.",
       "It’s so hot I saw a funeral procession pull through a Dairy Queen.",
       "It’s so hot cows are giving evaporated milk.",
       "It’s so hot, asphalt has a liquid state.",
       "It’s so hot I took off my flesh and sat on my bones.",
       "It’s so hot I saw a bird pull a worm out of the ground with an oven mitt.",
       "It’s so hot the Statue of Liberty was asked to lower her arm.",
       "It’s so hot, chickens are laying hard-boiled eggs.",
       "It’s so hot, E.L. James titled her next book Fifty Shades of Red. ",
       "It’s so hot they installed a fan in the debt ceiling.",
       "It’s so hot, polar bears are wearing sunscreen.",
       "It’s so hot, I discovered my seat belt makes a pretty good branding iron.",
       "It’s so hot granny broke wind just to have a little breeze.",
       "It’s so hot, I started putting ice-cubes in my waterbed.",
       "It’s so hot I set the house on fire just to cool off.",
       "It’s so hot we had to ship the fish to Seattle just so they wouldn’t forget how to swim.",
       "It’s so hot, Optimus Prime transformed into an air conditioner.",
       "It’s so hot Siri asked to be dipped in a glass of ice water.",
       "It’s so hot bums are holding signs that read, “Will work for shade.”",
       "It’s so hot fire ants are really on fire.",
       "It’s so hot, hot water comes out of both taps. (This one is actually true!)",
       "It’s so hot, I get condensation on my backside from the hot water in the toilet bowl.",
       "It’s so hot, the Betty Ford Clinic opened a wet bar.",
       "It’s so hot, Jehovah’s Witnesses started telemarketing.",
       "It’s so hot, I saw a dog chasing a cat and they were both walking.",
       "It’s so hot, I saw a fire hydrant chasing a dog."]

